# Generated by Django 2.2.6 on 2019-11-07 06:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fakeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakedata',
            name='company',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
